// @ts-check
// Copyright (c) 2026, MariaDB plc.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License, version 2.0,
// as published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
// the GNU General Public License, version 2.0, for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

// Offline preview of the MariaDB Shell reference docs.
//
// The pages in content/ are GitBook source: Markdown plus GitBook blocks,
// a SUMMARY.md for navigation, and `.gitbook/assets/` for images. They are
// written to be copied into the Enterprise Tools space of mariadb-docs
// (`tools/`) unchanged. This site only renders them, styled after
// https://mariadb.com/docs/, because GitBook itself cannot build offline.

import fs from 'node:fs';
import { themes as prismThemes } from 'prism-react-renderer';
import { remarkGitBook, rehypeGitBook } from 'docusaurus-plugin-gitbook';
import remarkGitBookExtras, { remarkGitBookPrepare } from './src/remark/gitbook-extras.js';

const REPO = 'https://github.com/mariadb-corporation/mariadb-shell';
const LIVE_DOCS = 'https://mariadb.com/docs';

// The space tabs of mariadb.com/docs, in their published order. The
// reference docs belong to Enterprise Tools, which is the one tab served
// locally; the others link out to the live site.
const SPACE_TABS = [
  { label: 'Home', href: `${LIVE_DOCS}` },
  { label: 'MariaDB Platform', href: `${LIVE_DOCS}/platform` },
  { label: 'Server', href: `${LIVE_DOCS}/server` },
  { label: 'MaxScale', href: `${LIVE_DOCS}/maxscale` },
  { label: 'Analytics', href: `${LIVE_DOCS}/analytics` },
  { label: 'Galera Cluster', href: `${LIVE_DOCS}/galera-cluster` },
  { label: 'Connectors', href: `${LIVE_DOCS}/connectors` },
  { label: 'Enterprise Tools', to: '/tools/', active: true },
  { label: 'MariaDB Cloud', href: `${LIVE_DOCS}/mariadb-cloud` },
  { label: 'Release Notes', href: `${LIVE_DOCS}/release-notes` },
  { label: 'General Resources', href: `${LIVE_DOCS}/general-resources` },
];

const BASE_URL = (process.env.DOCS_BASE_URL || '/docs/').replace(/^\/?/, '/').replace(/\/?$/, '/');

// Writes build/.htaccess so Apache serves the site's own 404 page. The path
// has to be absolute, so it is generated from the base URL rather than kept
// in static/.
function apacheHtaccess() {
  return {
    name: 'apache-htaccess',
    async postBuild({ outDir, baseUrl }) {
      fs.writeFileSync(
        `${outDir}/.htaccess`,
        [
          '# Generated by docusaurus.config.js for Apache httpd.',
          `ErrorDocument 404 ${baseUrl}404.html`,
          '',
        ].join('\n'),
      );
    },
  };
}

function hasGitBookAssets() {
  const dir = new URL('./content/.gitbook/assets/', import.meta.url);
  return fs.existsSync(dir) && fs.readdirSync(dir).some((f) => !f.startsWith('.'));
}

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'MariaDB Documentation',
  tagline: 'MariaDB Shell reference (offline preview)',
  favicon: 'img/favicon.ico',

  // Mirrors the published layout: https://mariadb.com/docs/tools/<product>/…
  // To host the preview under another path, build with e.g.
  // DOCS_BASE_URL=/mariadb-shell-docs/ npm run build.
  url: 'https://mariadb.com',
  baseUrl: BASE_URL,
  // Every page is written as <page>/index.html, so any static web server
  // (Apache, nginx, GitHub Pages) serves it without rewrite rules.
  trailingSlash: true,

  onBrokenLinks: 'throw',
  onBrokenAnchors: 'warn',

  i18n: { defaultLocale: 'en', locales: ['en'] },

  // GitBook writes CommonMark, not MDX: `{% … %}` would break the MDX parser.
  markdown: {
    format: 'md',
    mermaid: false,
    hooks: { onBrokenMarkdownLinks: 'throw' },
  },

  // GitBook's `.gitbook/assets/x.png` is rewritten by the plugin to
  // `/assets/x.png`, which content/.gitbook serves. Docusaurus fails on an
  // empty static directory, so it is added only once it holds an asset.
  staticDirectories: ['static', ...(hasGitBookAssets() ? ['content/.gitbook'] : [])],

  stylesheets: [
    'https://fonts.googleapis.com/css2?family=Lato:wght@400;700;900&family=IBM+Plex+Mono:wght@400;500&display=swap',
    // GitBook `icon:` frontmatter names Font Awesome icons.
    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css',
  ],

  plugins: ['docusaurus-plugin-gitbook', apacheHtaccess],

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          path: 'content',
          routeBasePath: 'tools',
          sidebarPath: './sidebars.js',
          exclude: ['**/SUMMARY.md', '**/.gitbook/**'],
          editUrl: `${REPO}/edit/main/docs-ref/`,
          showLastUpdateTime: false,
          beforeDefaultRemarkPlugins: [remarkGitBookPrepare, remarkGitBook, remarkGitBookExtras],
          rehypePlugins: [rehypeGitBook],
        },
        blog: false,
        pages: false,
        theme: {
          customCss: './src/css/mariadb-gitbook.css',
        },
      }),
    ],
  ],

  customFields: {
    spaceTabs: SPACE_TABS,
  },

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      colorMode: {
        defaultMode: 'light',
        respectPrefersColorScheme: true,
      },
      announcementBar: {
        id: 'offline-preview',
        content:
          'Offline preview of the <b>MariaDB Shell</b> reference docs. The published version will live on <a href="https://mariadb.com/docs/tools">mariadb.com/docs</a>.',
        isCloseable: true,
      },
      navbar: {
        title: '',
        logo: {
          alt: 'MariaDB',
          src: 'img/mariadb-logo-light.png',
          srcDark: 'img/mariadb-logo-dark.png',
          href: '/tools/',
        },
        hideOnScroll: false,
        items: [
          {
            href: 'https://mariadb.com/downloads/',
            label: 'Download MariaDB',
            position: 'right',
            className: 'navbar-cta',
          },
          {
            href: 'https://mariadb.com/contact/?utm_medium=docs',
            label: 'Contact Us',
            position: 'right',
          },
        ],
      },
      docs: {
        sidebar: { hideable: false, autoCollapseCategories: false },
      },
      tableOfContents: { minHeadingLevel: 2, maxHeadingLevel: 4 },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.vsDark,
        additionalLanguages: ['bash', 'batch', 'powershell', 'json', 'sql', 'toml', 'yaml', 'ini'],
      },
    }),
};

export default config;
